#!/usr/bin/python
import os, sys
import subprocess


def main():
    if (sys.argv[1] == 'inc'):
        subprocess.run(['xbacklight', '-inc', '5'])
    if (sys.argv[1] == 'dec'):
        current = float(subprocess.check_output(['xbacklight', '-get']))
        if (current - 5 <= 1):
            subprocess.run(['xbacklight', '-set', '1'])
        else:
            subprocess.run(['xbacklight', '-dec', '5'])


main()
