" Kevin Phoenix's .vimrc

set nocompatible
filetype off

set shell=bash

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle plugin, required
Plugin 'VundleVim/Vundle.vim'

" Lightline, alternative to powerline
Plugin 'itchyny/lightline.vim'

" Git support, probably illegal
Plugin 'tpope/vim-fugitive'

" NERD Tree
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'

" Syntastic plugin, syntax checking
Plugin 'scrooloose/syntastic'

" Jedi-vim, auto-completion for python 
Plugin 'davidhalter/jedi-vim'

" Python, improved syntax highlighting
Plugin 'hdima/python-syntax'

" SimpylFold, improve code folding
" Plugin 'tmhedberg/SimpylFold'

call vundle#end()
filetype plugin indent on

"""
" Display stuff
"
"""
" Syntax Highlighting
syntax enable
" Colorscheme
colorscheme Tomorrow-Night
set t_Co=256
highlight Normal ctermbg=none
" Show line numbers
set number
set relativenumber
" Highligh current line
set cursorline
" Enable mouse to place cursor
set mouse=a
" Enable indent-based code folding
set foldmethod=indent
set foldlevel=99

" Fix backspace key
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Set default encoding
set encoding=utf8
set ffs=unix,dos,mac

" Use 4 spaces for tab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" Lightline
set laststatus=2
set noshowmode

"""
" NERD Tree
"""
" Set ctrl-n to open
map <C-n> :NERDTreeToggle<CR>
" Close vim when NERD Tree is the only remaining window
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Syntastic Reccomended 
" set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Map ESC to <C-c> to prevent delay when leaving insert mode
" imap <ESC> <C-c>
